name = "BatchIterators"
uuid = "4161f7c7-f4e7-47ff-bbcb-bc0b24702626"
authors = ["CHATALIC Antoine <antoine.chatalic@irisa.fr>"]
version = "0.1.1"

[deps]
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
